### ISSUE TITLE
OTO backups

### ISSUE THREAD

**Issue by hongcui** [biosemantics/oto#39]
I think OTO currently dump backups directly to my home directory. backups should be directed to a backup folder within OTO directory.

**Comment by danveno** [comment]
The backup folder can be configured in the configuration file. I have created a new folder named "otobackups" and set it the directory holding the backup sql files. In my opinion, it's safer than putting it under the web files folder for OTO. Is it OK?

**Comment by hongcui** [comment]
backups on the same machine is not very safe. Can you write a crontab to copy backups periodically (every 3 months, eg., ) to somewhere else, e.g. dropbox?

**Comment by hongcui** [comment]
is this done yet? If so, close the issue. Thanks

**Comment by danveno** [comment]
A script, https://github.com/andreafabrizi/Dropbox-Uploader, is used to upload the zipped backup file to my dropbox. I shared the dropbox with you. A crontab command is applied to repeat the upload command every 3 months on 10th. Related information can be found under Dropbox folder in your home directory.
We can see whether it works or not tomorrow.
