### ISSUE TITLE
[Urgent] Import multiple sentences for a term

### ISSUE THREAD

**Issue by hongcui** [biosemantics/oto#40]
I imported a test dataset with this content 

![image](https://cloud.githubusercontent.com/assets/831423/20145437/62c77ede-a65d-11e6-8eda-4c1ad902bf98.png)

Note I was trying to include 2 sentences for the term 'term1'.

Importing was reported successful. I opened the dataset from Home 

![image](https://cloud.githubusercontent.com/assets/831423/20145692/50e9ce50-a65e-11e6-8778-5c2a08fba51c.png)

and the dataset is displayed in Group Terms UI, but it only showed one sentence in Context tab:
![image](https://cloud.githubusercontent.com/assets/831423/20145492/8da698ce-a65d-11e6-9186-66ae351809bf.png)

The import format instruction http://biosemantics.arizona.edu:8080/OTO/intro.do#csvFormat_Terms
didn't specify how to import multiple sentences for a term.  What I did was repeating the term for each sentence. I think that is easier to process than listing multiple sentences for one term on a row. 

Could you look into this and let me know can this be easily fixed asap? I would like to use this in a week or two to categorize the modifiers. Thanks,

**Comment by danveno** [comment]
The two sentences are imported sucessfully according to the DB records.
![image](https://cloud.githubusercontent.com/assets/5811267/20149749/e1ff16aa-a66f-11e6-9e4c-d3de27f498ec.png)
So, the problem is about retrieving them from DB. It should be easy to fix.

**Comment by danveno** [comment]
The original function grouped the sentences by source. One sentence is kept for one source and the maximum number of sources are 100. Now I relief these restrictions, no grouping and no limitation of sources. Does this work?

The change has been updated in the web application.

**Comment by hongcui** [comment]
I see. I think this works. Did you update OTO?

**Comment by danveno** [comment]
Yeah. The application in the server has been updated.
